### ISSUE TITLE
pass anthropic-version and model as parameters

### ISSUE THREAD

**Issue by MSIH** [tghamm/Anthropic.SDK#2]
Currently the version and model are hard coded.

- allow set as parameter
- allow set as environment variable

**Comment by tghamm** [comment]
@MSIH Hi, model is an exposed input parameter (you could change to 'claude-2.0' for instance), but you're right about anthropic-version. That was an intentional choice given the gravity of the changes between their initial release and the 06-01 version, I kind of assumed the library would need adaptation like their fully supported ones did in a future version, but I can expose it if you feel like that would be the better choice.  Thoughts?

**Comment by MSIH** [comment]
I am not clear on how the version and the model work together. Is the version the date of content used to create the model?

I just hate hard-coded values. they work until they don't. nice to have but not necessary. ideally would expose and set a default value.

**Comment by tghamm** [comment]
The model refers to the version of Claude that you are calling, (i.e. Claude Instant, Claude 2) - see [https://docs.anthropic.com/claude/reference/selecting-a-model](https://docs.anthropic.com/claude/reference/selecting-a-model).  The anthropic-version refers to the version of the api that's being called under the hood (there's only two versions, and only one that's not deprecated), as described here: [https://docs.anthropic.com/claude/reference/versioning](https://docs.anthropic.com/claude/reference/versioning).  That said, happy to expose the anthropic-version with a default already set.  I'll also update the README to show using the claude-2.0 family as the primary model of use as that was released just this week.  As it takes a model as input, it's not hard-coded, but the documentation shows 1.3, which is now out of date.
