### ISSUE TITLE
allow "type" json property on tools

### ISSUE THREAD

**Issue by fstandhartinger** [tghamm/Anthropic.SDK#54]
Hi there, kudos for the project!
For the new comupter use feature it would be necessary to provide a type property on the tool.

See here:
https://docs.anthropic.com/en/docs/build-with-claude/computer-use#computer-tool

![image](https://github.com/user-attachments/assets/8d496b98-6a67-4352-acd2-30d45ec349c0)

A minimal solution would be if the Function class wouldn't be sealed, I guess.

Then I could make a subclass that has the type property.

But of course a complete comuter use implementation would be highly appreciated.

**Comment by codegefluester** [comment]
Came here looking for the same thing. I tried working around it by cloning the project and adding it as a dependency while making some changes directly to the `Common.Tool` class but wasn't successful.

Did you find a workaround, @fstandhartinger?

**Comment by tghamm** [comment]
I'm actively working on this, have it mostly done.  Should have a release in a few days, just want to test some more.

**Comment by codegefluester** [comment]
> I'm actively working on this, have it mostly done. Should have a release in a few days, just want to test some more.

That's great to hear! Let me know if you want additional testers, we'd be happy to give it a go!

**Comment by fstandhartinger** [comment]
sorry, @codegefluester, missed your comment.
I had introduced a `public Func<string,string> ModifyRequestJsonFunc { get; set; }` in `EndpointBase` in order to inject my special needs into the json before it was sent to Anthropic.
But that's merely more than a ugly hack.
I am sure, @tghamm will solve it way more elegantly 💪

![image](https://github.com/user-attachments/assets/2f0cbbd0-2ea5-47df-9e30-518b429ffb87)

**Comment by tghamm** [comment]
There's a branch up, feature/4.4.0 - with an app called Anthropic.SDK.ComputerUse. In the current Sample app, the way it's prompted, it relies on Chrome being open on another screen, and the user running on Windows 10/11. I have 3 monitors, so depending on which monitor you have configured, you may have to toy with which screenIndex to capture, what resolution it is, things like that, but it's working reliably on my setup.  Feel free to give it a go....carefully, it's not in a VM or Docker instance, which is why I made the example intentionally minimalist.  Would love some feedback before I roll this out, just keep in mind, folks will generally be on their own and responsible for the code that takes action, I just provided enough to maybe leave some breadcrumbs for those getting started and ensured that the SDK is capable of kickstarting the Tooling side of the API.  Feedback welcome!

**Comment by tghamm** [comment]
4.4.0 is out with support for computer use, along with an associated example.  Happy coding!
